-- Initial schema for DICOM Viewer application

-- Application Entities (PACS configurations)
CREATE TABLE application_entities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ae_title VARCHAR(16) NOT NULL UNIQUE,
    hostname VARCHAR(255) NOT NULL,
    port INTEGER NOT NULL CHECK (port >= 1 AND port <= 65535),
    ae_type VARCHAR(50) NOT NULL,
    description VARCHAR(255),
    dicomweb_url VARCHAR(255),
    query_retrieve_level VARCHAR(50) DEFAULT 'STUDY',
    is_default BOOLEAN DEFAULT FALSE,
    is_enabled BOOLEAN DEFAULT TRUE,
    connection_timeout INTEGER DEFAULT 30000,
    response_timeout INTEGER DEFAULT 60000,
    max_associations INTEGER DEFAULT 10,
    last_echo_status VARCHAR(50),
    last_echo_time TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);

-- Stored DICOM Instances
CREATE TABLE stored_instances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sop_instance_uid VARCHAR(255) NOT NULL UNIQUE,
    sop_class_uid VARCHAR(255),
    study_instance_uid VARCHAR(255) NOT NULL,
    series_instance_uid VARCHAR(255) NOT NULL,
    file_path VARCHAR(1024) NOT NULL,
    file_size BIGINT,
    transfer_syntax_uid VARCHAR(255),
    patient_id VARCHAR(255),
    patient_name VARCHAR(255),
    study_date VARCHAR(255),
    modality VARCHAR(255),
    instance_number INTEGER,
    rows INTEGER,
    columns INTEGER,
    stored_at TIMESTAMP NOT NULL,
    last_accessed_at TIMESTAMP
);

CREATE INDEX idx_sop_instance_uid ON stored_instances(sop_instance_uid);
CREATE INDEX idx_study_instance_uid ON stored_instances(study_instance_uid);
CREATE INDEX idx_series_instance_uid ON stored_instances(series_instance_uid);
CREATE INDEX idx_patient_id ON stored_instances(patient_id);

-- Annotations
CREATE TABLE annotations (
    id UUID PRIMARY KEY,
    study_instance_uid VARCHAR(255) NOT NULL,
    series_instance_uid VARCHAR(255) NOT NULL,
    sop_instance_uid VARCHAR(255) NOT NULL,
    image_id VARCHAR(255),
    frame_index INTEGER,
    annotation_type VARCHAR(50) NOT NULL,
    tool_name VARCHAR(255) NOT NULL,
    text TEXT,
    points_json TEXT NOT NULL,
    style_json TEXT,
    color VARCHAR(50),
    font_size INTEGER,
    visible BOOLEAN NOT NULL DEFAULT TRUE,
    locked BOOLEAN NOT NULL DEFAULT FALSE,
    created_by VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);

CREATE INDEX idx_annotation_study ON annotations(study_instance_uid);
CREATE INDEX idx_annotation_series ON annotations(series_instance_uid);
CREATE INDEX idx_annotation_sop ON annotations(sop_instance_uid);
CREATE INDEX idx_annotation_user ON annotations(created_by);

-- Measurements
CREATE TABLE measurements (
    id UUID PRIMARY KEY,
    study_instance_uid VARCHAR(255) NOT NULL,
    series_instance_uid VARCHAR(255) NOT NULL,
    sop_instance_uid VARCHAR(255) NOT NULL,
    image_id VARCHAR(255),
    frame_index INTEGER,
    measurement_type VARCHAR(50) NOT NULL,
    tool_name VARCHAR(255) NOT NULL,
    label VARCHAR(255),
    measurement_value DOUBLE PRECISION,
    unit VARCHAR(50),
    points_json TEXT NOT NULL,
    roi_stats_json TEXT,
    color VARCHAR(50),
    visible BOOLEAN NOT NULL DEFAULT TRUE,
    created_by VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);

CREATE INDEX idx_measurement_study ON measurements(study_instance_uid);
CREATE INDEX idx_measurement_series ON measurements(series_instance_uid);
CREATE INDEX idx_measurement_sop ON measurements(sop_instance_uid);
CREATE INDEX idx_measurement_user ON measurements(created_by);

-- Key Images
CREATE TABLE key_images (
    id UUID PRIMARY KEY,
    study_instance_uid VARCHAR(255) NOT NULL,
    series_instance_uid VARCHAR(255) NOT NULL,
    sop_instance_uid VARCHAR(255) NOT NULL,
    image_id VARCHAR(255),
    frame_index INTEGER,
    instance_number INTEGER,
    description TEXT,
    category VARCHAR(255),
    window_width DOUBLE PRECISION,
    window_center DOUBLE PRECISION,
    thumbnail_path VARCHAR(1024),
    created_by VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT uk_key_image_sop_frame UNIQUE (sop_instance_uid, frame_index)
);

CREATE INDEX idx_key_image_study ON key_images(study_instance_uid);
CREATE INDEX idx_key_image_series ON key_images(series_instance_uid);
CREATE INDEX idx_key_image_sop ON key_images(sop_instance_uid);
CREATE INDEX idx_key_image_user ON key_images(created_by);

-- Audit Log
CREATE TABLE audit_log (
    id UUID PRIMARY KEY,
    user_id VARCHAR(255),
    username VARCHAR(255),
    action VARCHAR(255) NOT NULL,
    resource_type VARCHAR(255),
    resource_id VARCHAR(255),
    details TEXT,
    timestamp TIMESTAMP NOT NULL,
    ip_address VARCHAR(45)
);

CREATE INDEX idx_audit_log_user ON audit_log(user_id);
CREATE INDEX idx_audit_log_action ON audit_log(action);
CREATE INDEX idx_audit_log_timestamp ON audit_log(timestamp);

-- Study Cache
CREATE TABLE study_cache (
    study_instance_uid VARCHAR(64) PRIMARY KEY,
    patient_id VARCHAR(64),
    patient_name VARCHAR(255),
    patient_birth_date DATE,
    patient_sex VARCHAR(1),
    study_date DATE,
    study_time VARCHAR(14),
    study_description VARCHAR(255),
    modality VARCHAR(16),
    accession_number VARCHAR(16),
    referring_physician_name VARCHAR(255),
    number_of_series INTEGER,
    number_of_instances INTEGER,
    source_pacs_id UUID,
    local_path VARCHAR(255),
    cached_at TIMESTAMP
);

CREATE INDEX idx_study_cache_patient ON study_cache(patient_id);
CREATE INDEX idx_study_cache_date ON study_cache(study_date);
CREATE INDEX idx_study_cache_modality ON study_cache(modality);

-- PACS Configuration
CREATE TABLE pacs_configuration (
    id UUID PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    host VARCHAR(255) NOT NULL,
    port INTEGER NOT NULL,
    ae_title VARCHAR(16) NOT NULL,
    pacs_type VARCHAR(50) NOT NULL,
    wado_rs_url VARCHAR(500),
    qido_rs_url VARCHAR(500),
    stow_rs_url VARCHAR(500),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE INDEX idx_pacs_config_name ON pacs_configuration(name);
CREATE INDEX idx_pacs_config_active ON pacs_configuration(is_active);

